// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

package testutil

import (
	"bytes"
	"context"
	"os"
	"path"
	"path/filepath"
	"runtime"
	"testing"
	"time"

	cloudwatchlogstypes "github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs/types"
	"gopkg.in/yaml.v2"

	awssdk "github.com/aws/aws-sdk-go-v2/aws"
	awsConfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
)

const (
	// LogGroupNamePrefix matches the prefix used by _meta/terraform resources.
	LogGroupNamePrefix = "filebeat-log-group-integtest-"

	terraformOutputYML = "_meta/terraform/outputs.yml"
)

// TerraformOutputs contains AWS resources created by terraform apply.
type TerraformOutputs struct {
	AWSRegion  string `yaml:"aws_region"`
	LogGroup1  string `yaml:"log_group_name_1"`
	LogGroup2  string `yaml:"log_group_name_2"`
	LogStream1 string `yaml:"log_stream_name_1"`
	LogStream2 string `yaml:"log_stream_name_2"`
}

// GetTerraformOutputs loads outputs.yml generated by terraform apply.
func GetTerraformOutputs(t *testing.T) TerraformOutputs {
	t.Helper()

	_, filename, _, _ := runtime.Caller(0)
	ymlPath := path.Join(path.Dir(filename), "..", terraformOutputYML)
	ymlData, err := os.ReadFile(ymlPath)
	if os.IsNotExist(err) {
		t.Skipf("Run 'terraform apply' in %v to set up CloudWatch resources for the test.", filepath.Dir(ymlPath))
	}
	if err != nil {
		t.Fatalf("failed reading terraform output data: %v", err)
	}

	var outputs TerraformOutputs
	dec := yaml.NewDecoder(bytes.NewReader(ymlData))
	dec.SetStrict(true)
	if err = dec.Decode(&outputs); err != nil {
		t.Fatal(err)
	}

	return outputs
}

// NewCloudWatchLogsClient returns a CloudWatch Logs client using the default AWS config chain.
func NewCloudWatchLogsClient(t *testing.T, region string) *cloudwatchlogs.Client {
	t.Helper()

	cfg, err := awsConfig.LoadDefaultConfig(context.TODO())
	if err != nil {
		t.Fatal(err)
	}
	cfg.Region = region

	return cloudwatchlogs.NewFromConfig(cfg)
}

// UploadLogMessage writes a log event to the given log group and stream.
func UploadLogMessage(t *testing.T, svc *cloudwatchlogs.Client, message string, logGroupName, logStreamName string) {
	t.Helper()

	describeLogStreamsInput := cloudwatchlogs.DescribeLogStreamsInput{
		LogGroupName:        awssdk.String(logGroupName),
		LogStreamNamePrefix: awssdk.String(logStreamName),
	}

	resp, err := svc.DescribeLogStreams(context.TODO(), &describeLogStreamsInput)
	if err != nil {
		t.Fatalf("failed to describe log stream %q in log group %q: %v", logStreamName, logGroupName, err)
	}

	if len(resp.LogStreams) != 1 {
		t.Fatalf("describe log stream %q in log group %q should return 1 and only 1 value", logStreamName, logGroupName)
	}

	timestamp := time.Now().UnixMilli()
	inputLogEvent := cloudwatchlogstypes.InputLogEvent{
		Message:   awssdk.String(message),
		Timestamp: awssdk.Int64(timestamp),
	}

	_, err = svc.PutLogEvents(context.TODO(), &cloudwatchlogs.PutLogEventsInput{
		LogEvents:     []cloudwatchlogstypes.InputLogEvent{inputLogEvent},
		LogGroupName:  awssdk.String(logGroupName),
		LogStreamName: awssdk.String(logStreamName),
		SequenceToken: resp.LogStreams[0].UploadSequenceToken,
	})
	if err != nil {
		t.Fatalf("failed to upload message %q into log stream %q in log group %q: %v", message, logStreamName, logGroupName, err)
	}
}
